### ISSUE TITLE
PosPaymentLocalApi throws HttpException 408 when connecting to terminal

### ISSUE THREAD

**Issue by craftbyte** [Adyen/adyen-dotnet-api-library#358]
**Describe the bug**
When using PosPaymentLocalApi to send a SaleToPOIRequest it throws a 408 exception.

**To Reproduce**
See example code in https://gist.github.com/craftbyte/3bf4416335972a95b5757253eaa2bfe2.

**Expected behavior**
Payment goes through to terminal

**Additional context**
When setting a proxy to the client somehow the request goes through normally.

**Exception details**
```
Adyen.HttpClient.HttpClientException
  HResult=0x80131500
  Message=HTTP Exception timeout
  Source=Adyen
  StackTrace:
   at Adyen.HttpClient.HttpUrlConnectionClient.Request(String endpoint, String json, Config config, Boolean isApiKeyRequired, RequestOptions requestOptions)
   at Adyen.Service.ServiceResource.Request(String json, RequestOptions requestOptions)
   at Adyen.Service.PosPaymentLocalApi.TerminalApiLocal(SaleToPOIMessage saleToPoiRequest, EncryptionCredentialDetails encryptionCredentialDetails)
   at AdyenDemo.Program.Main(String[] args) in C:\Users\anzej\source\repos\AdyenDemo\AdyenDemo\Program.cs:line 61
```

**Comment by craftbyte** [comment]
After recompiling it seems like the issue is actually an SSL exception.
"The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure."

What is the correct way to add certificates?

**Comment by AlexandrosMor** [comment]
Hello @craftbyte,

Thank you for contacting us. SSL exception means that the certificate is not installed in the host. The  certificate is used in local communication. The certificate needs to be installed in the CA store in trusted root certificates. 
Furthermore we are planning to improve the exception handling.
Let us know if it helps 

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @craftbyte,

We are going to close this issue. If you have more questions please do not hesitate to contact us or open another github issue.

kind regards,
Alexandros

**Comment by vivekadvsol** [comment]
Hi,
I am also getting same error. I wonder how to I overcome this?

 ```
Private Function MakeSales() As Boolean
        Try

            Dim config As New Adyen.Config()

            config.Endpoint = "https://192.168.0.9:8443/nexo/"
            config.ApplicationName = "RMS"
            config.Environment = Model.Enum.Environment.Test
            config.HttpRequestTimeout = 120
            config.MerchantAccount = "MERCHENACCOUNT"
            config.XApiKey = "MYAPIKEY"

            Dim myClient As New Client(config)

            Dim encryptionCredentialDetails As New EncryptionCredentialDetails()

            encryptionCredentialDetails.AdyenCryptoVersion = 1
            encryptionCredentialDetails.KeyIdentifier = "KEYIDENTIFIER"
            encryptionCredentialDetails.Password = "PASSWORD"
            encryptionCredentialDetails.KeyVersion = 1

            Dim posPaymentLocalApi As New Adyen.Service.PosPaymentLocalApi(myClient)

            '1.SaleToPOIRequest
            Dim myRequest As New Model.Nexo.Message.SaleToPOIRequest()

            '2.Header
            Dim myReq_MessageHeader As New Model.Nexo.MessageHeader()

            'Load Header
            myReq_MessageHeader.MessageClass = MessageClassType.Service
            myReq_MessageHeader.MessageCategory = MessageCategoryType.Payment
            myReq_MessageHeader.MessageType = MessageType.Request
            myReq_MessageHeader.SaleID = "Test01"
            myReq_MessageHeader.ServiceID = "R129011018"
            myReq_MessageHeader.POIID = "P400Plus-XXXXXXXX"

            '3.Payload
            Dim myPayRequest_PayLoad As New Model.Nexo.PaymentRequest() 'For Body

            '3a.Sale Data & Transaction Id
            Dim myReq_SalesData As New Model.Nexo.SaleData()
            Dim myReq_TransactionID As New Model.Nexo.TransactionIdentification()
            myReq_TransactionID.TransactionID = "Reg012901211018"
            myReq_TransactionID.TimeStamp = DateTime.Now.Date
            myReq_SalesData.SaleTransactionID = myReq_TransactionID

            '3b.PaymentTransaction and 'Amount Req
            Dim myReq_PaymentTransaction As New Model.Nexo.PaymentTransaction()
            Dim myReq_Amount As New Model.Nexo.AmountsReq()

            myReq_Amount.Currency = "AUD"
            myReq_Amount.RequestedAmount = 9.99
            myReq_PaymentTransaction.AmountsReq = myReq_Amount

            '4. Attach Sale Data and Payment Transaction to Payload / PaymentRequest
            myPayRequest_PayLoad.SaleData = myReq_SalesData
            myPayRequest_PayLoad.PaymentTransaction = myReq_PaymentTransaction

            myRequest.MessageHeader = myReq_MessageHeader 'Header
            myRequest.MessagePayload = myPayRequest_PayLoad 'Body
            myRequest.SecurityTrailer = New ContentInformation()

            Dim myResponse As New Model.Nexo.SaleToPOIResponse()

            '5. Make the request
            myResponse = posPaymentLocalApi.TerminalApiLocal(myRequest, encryptionCredentialDetails)
            MessageBox.Show(myResponse.MessagePayload.ToString())

            Return True

        Catch ex As Exception
            MessageBox.Show(ex.Message)
            Throw New Exception($"Error: {ex}")
        End Try

    End Function
```

The exception is as follows,
````
exception	{"HTTP Exception timeout"}	Adyen.HttpClient.HttpClientException
		Code	408	Integer
```
+		Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
+		Exception	{"The operation has timed out"}	System.Exception {System.Net.WebException}
		HResult	-2146233088	Integer
		HelpLink	Nothing	String
+		InnerException	Nothing	System.Exception
		JsonResponse	Nothing	String
		Message	"HTTP Exception timeout"	String
		ResponseBody	"No response"	String
		Source	"Adyen"	String
		StackTrace	"   at Adyen.HttpClient.HttpUrlConnectionClient.Request(String endpoint, String json, Config config, Boolean isApiKeyRequired, RequestOptions requestOptions)" & vbCrLf & "   at Adyen.Service.ServiceResource.Request(String json, RequestOptions requestOptions)" & vbCrLf & "   at Adyen.Service.PosPaymentLocalApi.TerminalApiLocal(SaleToPOIMessage saleToPoiRequest, EncryptionCredentialDetails encryptionCredentialDetails)" & vbCrLf & "   at AdvantageAdyen.AdvantageAdyen.MakeSales() in C:\OneDrive\OneDrive - Advantage Solutions\Projects\Zoo\AdvantageAdyen\AdvantageAdyen.vb:line 112"	String
`
