### ISSUE TITLE
Callling checkout.PaymentsDetails(paymentsDetailsRequest) throws an exception

### ISSUE THREAD

**Issue by akScript** [Adyen/adyen-dotnet-api-library#373]
**Bug description:**
when using Adyen Drop-in for web, calling checkout.PaymentsDetails(paymentsDetailsRequest) in other to perform the additional checks in case of 3DS payments, which is [this step](https://docs.adyen.com/online-payments/drop-in-web#step-5-additional-payment-details), an exception is thrown:

Message: 
`Could not create an instance of type Adyen.Model.Checkout.Action.IPaymentResponseAction. Type is an interface or abstract class and cannot be instantiated. Path 'action.paymentData', line 1, position 57.`

StackTrack:
   `at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Adyen.Service.Checkout.PaymentDetails(PaymentsDetailsRequest paymentsDetailsRequest, RequestOptions requestOptions)
`

**Steps to reproduce:**
1- implement steps on [Web Drop-in integration guide ](https://docs.adyen.com/online-payments/drop-in-web#step-5-additional-payment-details)
2- use a 3DS 2 test card for instance (Visa | 4917 6100 0000 0000 | 03/2030 | 737)
3- pass `state.data` you get from the front end to your server
4- call checkout.PaymentsDetails(paymentsDetailsRequest) using data in `state.data`

Adyen .net Package version: 6.0.0
@adyen/adyen-web version : "3.20.0"

**Comment by AlexandrosMor** [comment]
Hello @akScript,
Thank you for raising this issue. Similar to #374 I think is the same issue
We added the type data member annotation in develop for example. It would be great help for us to check if develop branch works for you and let us know so we can do the release with the fix asap

kind regards,
Alexandros

**Comment by akScript** [comment]
Hello @AlexandrosMor
I have tested the change in develop but it did not fix this issue.

**Comment by AlexandrosMor** [comment]
Hello @akScript,

It would be great if you could add the json here that is causing this issue so I can create a unit test based on it and fix the issue. Please replace any data with dummy.

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @akScript,

Could you please check if this [pull request](https://github.com/Adyen/adyen-dotnet-api-library/pull/375) fix the issue for you ? 
regards,
Alexandros

**Comment by akScript** [comment]
Hello @AlexandrosMor
I tested the pull request and it seems to work now
![Capture1](https://user-images.githubusercontent.com/77968688/105753809-8eebc700-5f49-11eb-9e29-b6ed3b0a07b5.PNG)![Capture2](https://user-images.githubusercontent.com/77968688/105753834-94e1a800-5f49-11eb-86ad-5d5e1f236a23.PNG)
however, after completing the challenge (clicking submit on the second image) nothing happens, the area becomes empty. it might not necessarily be related to this issue
