### ISSUE TITLE
Applepay failed HTTP Exception

### ISSUE THREAD

**Issue by lyjgiggs** [Adyen/adyen-dotnet-api-library#451]
Tried both ApplePayDetails and DefaultPaymentMethodDetails and had the same issue.  Configuration is working fine for credit card / 3ds 1 and 2 / Googlepay and other redirect methods. 

Exception Message: HTTP Exception
Exception StackTrace:    

   at Adyen.HttpClient.HttpUrlConnectionClient.HandleWebException(WebException e)
   at Adyen.HttpClient.HttpUrlConnectionClient.Request(String endpoint, String json, Config config, Boolean isApiKeyRequired, RequestOptions requestOptions)
   at Adyen.Service.ServiceResource.Request(String json, RequestOptions requestOptions)
   at Adyen.Service.Checkout.Payments(PaymentRequest paymentRequest, RequestOptions requestOptions)

**Comment by lyjgiggs** [comment]
Could be Adyen server issue. Will check with it first.
