### ISSUE TITLE
PosPaymentLocalApi#TerminalApiLocal() Throws an HTTP Exception: "Potential certificate mismatch"

### ISSUE THREAD

**Issue by cryptidv** [Adyen/adyen-dotnet-api-library#635]
Hi!

**Issue:**
When I make a request to the configured Local Terminal it throws 
> **`Adyen.HttpClient.HttpClientException: Potential certificate mismatch`.**

**The terminal and my credentials are properly configured**, I made a prototype application with the NodeJS library and it worked perfectly.

I have also properly installed the Adyen root certificates as described [here](https://docs.adyen.com/point-of-sale/choose-your-architecture/local?tab=windows_environment_2#protect-communications).

**Additional Info:**
Terminal: Castles S1E
Target Framework: .NET 6.0
The Application is an ASP.net REST API.

I looked through the library and noticed that this message is provided when microsoft returns an "Unknown Error" after an Http Request. But I cannot figure why this is not working, any help would be greatly appreciated!

**Exception:**
```
Adyen.HttpClient.HttpClientException: Potential certificate mismatch
   at Adyen.HttpClient.HttpUrlConnectionClient.HandleWebException(WebException e)
   at Adyen.HttpClient.HttpUrlConnectionClient.Request(String endpoint, String json, Config config, Boolean isApiKeyRequired, RequestOptions requestOptions)
   at Adyen.Service.ServiceResource.Request(String json, RequestOptions requestOptions)
   at Adyen.Service.PosPaymentLocalApi.TerminalApiLocal(SaleToPOIMessage saleToPoiRequest, EncryptionCredentialDetails encryptionCredentialDetails)
   at PaymentDeviceAPI.Devices.AdyenDevice.InitiateTransaction(Single amount) in C:\Users\96655\Documents\PaymentDeviceAPI\Devices\Adyen\AdyenDevice.cs:line 130
   at PaymentDeviceAPI.Controllers.PaymentsController.CreatePayment(PaymentSimplified paymentReq) in C:\Users\96655\Documents\PaymentDeviceAPI\Controllers\PaymentsController.cs:line 39
   at lambda_method2(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Code:**
```cs
...
// Creating Credentials
encryptionCredentialDetails = new EncryptionCredentialDetails
{ 
	  AdyenCryptoVersion = 1,
	  KeyIdentifier = keyId,
	  Password = passwd,
	  KeyVersion = keyVer
};
...
// Configuring and Creating the Client
Config config = new()
{ 
	  MerchantAccount = acc,
	  XApiKey = token,
	  Endpoint = $"https://{RegisteredDevice.Address}/nexo",
	  Environment = Adyen.Model.Enum.Environment.Test, 
};
Client client = new(config);
paymentApi = new(client); // Type is PosPaymentLocalApi
...
// Creating payment
var req = new AdyenPaymentRequest()
{
	  SaleData = new
	  { 
	  	SaleTransactionID = new() 
	  	{
		    ["TransactionID"] = newPaymentId,
		    ["TimeStamp"] = timeNow
	  	},
	  },
	  PaymentTransaction = new()
	  {
	  	AmountsReq = new()
	  	{
		    Currency = "AED",
		    RequestedAmount = amount
	 	 }
	  }
};
...
SaleToPOIMessage msg = new()
{
    MessageHeader = new()
    {
        MessageClass = MessageClassType.Service,
        MessageCategory = MessageCategoryType.Payment,
        ServiceID = newPaymentId, // Payment 
        SaleID = Client.Id ?? "DEV_?",
        POIID = RegisteredDevice.Terminal.Poiid,
    },
    MessagePayload = req
};

var response = paymentApi.TerminalApiLocal(msg, encryptionCredentialDetails); // Throws the exception
```

**Comment by AlexandrosMor** [comment]
Hello @cryptidv,

Thank you for contacting us, If you installed the certificate in the CA store of windows it should be possible to build the certificate chain. The error it might be different based in the [httpclient](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/HttpClient/HttpURLConnectionClient.cs#L127). Is it possible to debug the issue ? 

kind regards,
Alexandros
Adyen
