### ISSUE TITLE
v.10.1.0 Direct request to pinpad error "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel"

### ISSUE THREAD

**Issue by igorpooh1978** [Adyen/adyen-dotnet-api-library#835]
**Describe the bug**
We develop our application with direct connection to pinpad only (windows).
We install both CA certificate into Trusted CA
I connect to Verifone pinpad directly https://[localip]:8443/nexo 
```C#
            var response = paymentApi.TerminalApiLocal(request, encryptionCredentialDetails);
```
There is I catch error 

```C#
(DEBUG ADYEN) Request: 
{"SaleToPOIRequest":{"MessageHeader":{"MessageClass":"Service","MessageCategory":"Diagnosis","MessageType":"Request","ServiceID":"143117-dg","SaleID":"KrispyKremeCHPOS","POIID":"S1F2-000158213608799","ProtocolVersion":"3.0"},"DiagnosisRequest":{"HostDiagnosisFlag":true}}}
[2023-06-30 14:31:17,856] ERROR [ 1] - Couldn't create plugin instance, constructor thrown an exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Adyen.HttpClient.HttpClientWrapper.<RequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Adyen.HttpClient.HttpClientWrapper.Request(String endpoint, String requestBody, RequestOptions requestOptions, HttpMethod httpMethod)
   at Adyen.Service.ServiceResource.Request(String json, RequestOptions requestOptions, HttpMethod httpMethod)
   at Adyen.Service.PosPaymentLocalApi.TerminalApiLocal(SaleToPOIMessage saleToPoiRequest, EncryptionCredentialDetails encryptionCredentialDetails)
   at Resto.Front.Api.AdyenPaymentPlugin.Uploader.AdyenUploader.DirectRequest(SaleToPOIRequest request)
   at Resto.Front.Api.AdyenPaymentPlugin.Uploader.AdyenUploader.Diagnosis()
   at Resto.Front.Api.AdyenPaymentPlugin.AdyenPayment.ShowDiagnosis(IViewManager vm)
   at Resto.Front.Api.AdyenPaymentPlugin.AdyenPayment..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Resto.Front.Api.Host.PluginRunner.TryCreatePluginInstance(Type pluginType) in M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api.Host\PluginRunner.cs:line 244
[2023-06-30 14:31:17,856] ERROR [ 1] - InnerException:
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Adyen.HttpClient.HttpClientWrapper.<RequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Adyen.HttpClient.HttpClientWrapper.Request(String endpoint, String requestBody, RequestOptions requestOptions, HttpMethod httpMethod)
   at Adyen.Service.ServiceResource.Request(String json, RequestOptions requestOptions, HttpMethod httpMethod)
   at Adyen.Service.PosPaymentLocalApi.TerminalApiLocal(SaleToPOIMessage saleToPoiRequest, EncryptionCredentialDetails encryptionCredentialDetails)
   at Resto.Front.Api.AdyenPaymentPlugin.Uploader.AdyenUploader.DirectRequest(SaleToPOIRequest request)
   at Resto.Front.Api.AdyenPaymentPlugin.Uploader.AdyenUploader.Diagnosis()
   at Resto.Front.Api.AdyenPaymentPlugin.AdyenPayment.ShowDiagnosis(IViewManager vm)
   at Resto.Front.Api.AdyenPaymentPlugin.AdyenPayment..ctor()
```   

**To Reproduce**
```C#
public AdyenUploader()
    {
        int timeout = Properties.Settings.Default.HttpTimeoutSec;
        if (timeout < 120)
            timeout = 120;
        config = new Config
        {
            ApplicationName = PluginHelpers.PluginName,
            MerchantAccount = Settings.Default.MerchantAccount,
            
            HttpRequestTimeout = timeout * 1000,
            //Environment = Adyen.Model.Enum.Environment.Test,
            //Endpoint =
            //   $"https://{Properties.Settings.Default.TerminalIpAddress}:{Properties.Settings.Default.TerminalPort}/nexo/",
            
           Timeout = timeout * 1000,
           Environment = Environment.Test,
             LocalTerminalApiEndpoint =
                $"https://{Settings.Default.TerminalIpAddress}:{Settings.Default.TerminalPort}/nexo/",
        };
        if (Settings.Default.EnableLiveMode)
        {
            //config.Environment = Adyen.Model.Enum.Environment.Live;
            
            config.Environment = Environment.Live;
            config.LiveEndpointUrlPrefix = Settings.Default.LiveEndpointUrlPrefix;
   
        }
        client = new Client(config);
       
        encryptionCredentialDetails = new EncryptionCredentialDetails
        {
            AdyenCryptoVersion = 1,
            KeyIdentifier = Settings.Default.KeyIdentifier,
            Password = Settings.Default.KeyPassphrase,
            KeyVersion = Settings.Default.KeyVersion
        };

        paymentApi = new PosPaymentLocalApi(client);
        paymentApi.Client.LogCallback += Client_LogCallback;
    }

    public DiagnosisResponse Diagnosis()
    {
        PluginContext.Log.Debug("AdyenUploader.Diagnosis :: started.");
        DiagnosisRequest diagnosisRequest = new DiagnosisRequest
        {
            HostDiagnosisFlag = true
        };

        var request = GenerateSOIMessage(diagnosisRequest, MessageCategoryType.Diagnosis,
// at 9.21 all working wll
            var response = paymentApi.TerminalApiLocal(request, encryptionCredentialDetails);

...
   }

 private SaleToPOIRequest GenerateSOIMessage(object payload, MessageCategoryType messageCategoryType,
        string serviceId)
    {
        return new SaleToPOIRequest
        {
            MessageHeader = new MessageHeader
            {
                MessageClass = MessageClassType.Service,
                MessageCategory = messageCategoryType,
                MessageType = MessageType.Request,
                ServiceID = serviceId,
                SaleID = Properties.Settings.Default.MerchantAccount,
                POIID =
                    $"{Properties.Settings.Default.ModelNamePinPad}-{Properties.Settings.Default.SerialNumberPinPad}",
            },

            MessagePayload = payload,
            SecurityTrailer = new ContentInformation { }
        };
    }
```

For me is very strange certificate at point of direct connection to nexo
![image](https://github.com/Adyen/adyen-dotnet-api-library/assets/47010778/10672efa-89cc-4ad7-949b-510bbc35aea5)

**Expected behavior**
I expected exactly the same reaction as for version 9.21.
An answer like this
```
{"SaleToPOIRequest":{"MessageHeader":{"MessageClass":"Service","MessageCategory":"Diagnosis","MessageType":"Request","ServiceID":"151603-dg","SaleID":"MyPOINT","POIID":"S1F2-00015821360xxx","ProtocolVersion":"3.0"},"NexoBlob":"p...","SecurityTrailer":{"AdyenCryptoVersion":1,"KeyIdentifier":"keyind","KeyVersion":1,"Nonce":"...==","Hmac":"..="}}}

```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by igorpooh1978** [comment]
Somebody answer to me

**Comment by jillingk** [comment]
Hi @igorpooh1978, 

Apologies for the delayed response! I've pinpointed the issue and will rollout a fix asap (hopefully on Monday already). I think from that, we can release it end of the week! 

Hope this timeline works for you.

Best, Jilling
Adyen

**Comment by igorpooh1978** [comment]
Thanks a lot !!!
