### ISSUE TITLE
Confusing error if payment terminal is missing encryption and client has encryption enabled

### ISSUE THREAD

**Issue by jsyrjala** [Adyen/adyen-dotnet-api-library#903]
**Describe the bug**

If client tries to use encrypted communication, but payment terminal has no encryption key configured, there is very confusing error message.

I guess this can happen e.g when payment terminal is assigned to another merchant account/store.

**To Reproduce**
Using local communications for ECR <-> PED and Adyen Development environment.

1. Setup client to use encryption keys
2. Setup payment terminal not to have encryption
3. Send from client e.g. DiagnosisRequest to the terminal
4. Parsing the response from payment terminal fails with System.NullReferenceException

**Expected behavior**

I'd expect the code to detect this situation and throw some exception that is more descriptive.  Exception should mention about decryption failing, missing encryption on the response or something along those lines.

**Desktop (please complete the following information):**
 - adyen-dotnet-api-library 11.1.2

**Additional context**

Request:
```json
{
  "MessageHeader": {
    "MessageClass": "Service",
    "MessageCategory": "Diagnosis",
    "MessageType": "Request",
    "ServiceID": "1A1FBB24DE",
    "DeviceID": null,
    "SaleID": "POSSystemID12345",
    "POIID": "S1F2-0001234567890",
    "ProtocolVersion": "3.0"
  },
  "MessagePayload": {
    "AcquirerID": null,
    "POIID": null,
    "HostDiagnosisFlag": false
  },
  "SecurityTrailer": null
}
```

Stacktrace
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Adyen.ApiSerialization.SaleToPoiMessageSecuredSerializer.ParseSaleToPoiMessageSecured(JToken saleToPoiMessageSecuredJToken)
   at Adyen.ApiSerialization.SaleToPoiMessageSecuredSerializer.Deserialize(String saleToPoiMessageSecuredJSon)
   at Adyen.Service.TerminalLocalApi.TerminalRequest(SaleToPOIMessage saleToPoiRequest, EncryptionCredentialDetails encryptionCredentialDetails)
```

**Comment by wboereboom** [comment]
hi @jsyrjala, 
Thanks for raising this issue.
We'll take some time to investigate whether we can make this a bit more intuitive.

Kind Regards,
Wouter
Adyen

**Comment by captador** [comment]
same issue still in 14.4.0 version

```
DiagnosisRequest failed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Adyen.ApiSerialization.SaleToPoiMessageSecuredSerializer.ParseSaleToPoiMessageSecured(JToken saleToPoiMessageSecuredJToken)
   at Adyen.ApiSerialization.SaleToPoiMessageSecuredSerializer.Deserialize(String saleToPoiMessageSecuredJSon)
   at Adyen.Service.TerminalLocalApi.TerminalRequest(SaleToPOIMessage saleToPoiRequest, EncryptionCredentialDetails encryptionCredentialDetails)
   ```
