### ISSUE TITLE
Version 14.1.0 TerminalSettingsTerminalLevelApi.getTerminalSettings() throws exception

### ISSUE THREAD

**Issue by jsyrjala** [Adyen/adyen-dotnet-api-library#989]
**Describe the bug**
With 14.1.0 we are seeing TerminalSettingsTerminalLevelApi.getTerminalSettings()  to throw exception in our test environment

Version 14.0.0 worked fine.

**To Reproduce**
- Make TerminalSettingsTerminalLevelApi.getTerminalSettings()  -> exception happens

**Expected behavior**
No expection should happen

**Desktop (please complete the following information):**
 - Linux, dotnet 6
 - Version 14.1.0

**Additional context**

One occurance with P400Plus-806475746 at 2024-03-05T07:02:37.561Z

Similar issue in java: https://github.com/Adyen/adyen-java-api-library/issues/1235

Stacktrace
```
error.message: Cannot construct instance of `com.adyen.model.management.Notification$CategoryEnum`, problem: Unexpected value ''
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 543] (through reference chain: com.adyen.model.management.TerminalSettings["nexo"]->com.adyen.model.management.Nexo["notification"]->com.adyen.model.management.Notification["category"])
   error.stack_trace: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.adyen.model.management.Notification$CategoryEnum`, problem: Unexpected value ''
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 543] (through reference chain: com.adyen.model.management.TerminalSettings["nexo"]->com.adyen.model.management.Nexo["notification"]->com.adyen.model.management.Notification["category"])
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:2014)
	at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1426)
	at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:205)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4899)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3846)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3814)
	at com.adyen.model.management.TerminalSettings.fromJson(TerminalSettings.java:836)
	at com.adyen.service.management.TerminalSettingsTerminalLevelApi.getTerminalSettings(TerminalSettingsTerminalLevelApi.java:117)
	at com.adyen.service.management.TerminalSettingsTerminalLevelApi.getTerminalSettings(TerminalSettingsTerminalLevelApi.java:95)
        at OUR CODE
Caused by: java.lang.IllegalArgumentException: Unexpected value ''
	at com.adyen.model.management.Notification$CategoryEnum.fromValue(Notification.java:73)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.callOnWith(AnnotatedMethod.java:118)
	at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:194)
	... 37 more
```

**Comment by jsyrjala** [comment]
Seems that this is actually stacktrace from adyen's java library. So issue is at least there. Not sure if dotnet library has same issue.

**Comment by DjoykeAbyah** [comment]
Hi @jsyrjala!

I've checked to be sure but the latest .Net library release should fix this issue in the same manner as in the Java library!
https://github.com/Adyen/adyen-dotnet-api-library/blob/dfab19a5d24790233a6b35a0b3404097089db214/Adyen/Model/Management/Notification.cs#L57

Kind regards,

Djoyke
Adyen
